name: "Draft new release"

on:
    workflow_dispatch:
        inputs:
            version:
                description: "The version you want to release."
                required: true

jobs:
    draft-new-release:
        name: "Draft a new release"
        runs-on: ubuntu-latest
        permissions:
            contents: write
            pull-requests: write
        steps:
            - uses: actions/checkout@v4

            - name: Create release branch
              run: git checkout -b release/${{ github.event.inputs.version }}

            - name: Update changelog
              uses: thomaseizinger/keep-a-changelog-new-release@3.1.0
              with:
                  tag: v${{ github.event.inputs.version }}

            - name: Format changelog
              run: npx prettier -w ./CHANGELOG.md

            # In order to make a commit, we need to initialize a user.
            - name: Initialize mandatory git config
              run: |
                  git config user.name "GitHub Actions"
                  git config user.email noreply@github.com

            - name: Install cargo-bump
              uses: taiki-e/install-action@v2
              with:
                  tool: cargo-bump

            - name: Bump version in Cargo.toml
              run: cargo bump ${{ github.event.inputs.version }}

            - name: Commit changelog and manifest files
              id: make-commit
              run: |
                  git add CHANGELOG.md Cargo.toml
                  git commit --message "chore: prepare release ${{ github.event.inputs.version }}"

                  echo "::set-output name=commit::$(git rev-parse HEAD)"

            - name: Push new branch
              run: git push origin release/${{ github.event.inputs.version }}

            - name: Create pull request
              uses: thomaseizinger/create-pull-request@1.4.0
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  head: release/${{ github.event.inputs.version }}
                  base: main
                  title: Release version ${{ github.event.inputs.version }}
                  reviewers: ${{ github.actor }}
                  body: |
                      Hi @${{ github.actor }}!

                      This PR was created in response to a manual trigger of the release workflow here: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}.
                      I've updated the changelog and bumped the versions in the manifest files in this commit: ${{ steps.make-commit.outputs.commit }}.

                      Merging this PR will create a GitHub release and upload any assets that are created as part of the release build.
