name: "Publish new release"

on:
    pull_request:
        branches:
            - main
        types:
            - closed

jobs:
    release:
        name: Publish new release
        runs-on: ubuntu-latest
        permissions:
            contents: write
        # only merged pull requests that begin with 'release/' or 'hotfix/' must trigger this job
        if: github.event.pull_request.merged == true &&
            (startsWith(github.event.pull_request.head.ref, 'release/') || startsWith(github.event.pull_request.head.ref, 'hotfix/'))

        steps:
            - name: Extract version from branch name (for release branches)
              if: startsWith(github.event.pull_request.head.ref, 'release/')
              run: |
                  BRANCH_NAME="${{ github.event.pull_request.head.ref }}"
                  VERSION=${BRANCH_NAME#release/}

                  echo "RELEASE_VERSION=$VERSION" >> $GITHUB_ENV

            - name: Extract version from branch name (for hotfix branches)
              if: startsWith(github.event.pull_request.head.ref, 'hotfix/')
              run: |
                  BRANCH_NAME="${{ github.event.pull_request.head.ref }}"
                  VERSION=${BRANCH_NAME#hotfix/}

                  echo "RELEASE_VERSION=$VERSION" >> $GITHUB_ENV

            - uses: actions/checkout@v4

            - name: Extract release notes
              id: extract-release-notes
              uses: ffurrer2/extract-release-notes@v2
              with:
                  changelog_file: CHANGELOG.md

            - name: Publish
              run: cargo publish --all-features
              env:
                  CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

            - name: Release
              uses: softprops/action-gh-release@v2
              with:
                  target_commitish: ${{ github.event.pull_request.merge_commit_sha }}
                  tag_name: v${{ env.RELEASE_VERSION }}
                  name: ${{ env.RELEASE_VERSION }}
                  draft: false
                  prerelease: false
                  body: |
                      ${{ steps.extract-release-notes.outputs.release_notes }}

                      https://crates.io/crates/${{ github.event.repository.name }}/${{ env.RELEASE_VERSION }}
